"""fix organization_id nullability and city_name unique constraint

Revision ID: 142a5db2006c
Revises: 7ebb7eafb3fe
Create Date: 2026-09-13 21:58:21.154028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142a5db2006c'
down_revision: Union[str, Sequence[str], None] = '7ebb7eafb3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_barangays_city'), table_name='barangays')
    op.drop_constraint(op.f('barangays_city_id_fkey'), 'barangays', type_='foreignkey')
    op.create_foreign_key(None, 'barangays', 'cities', ['city_id'], ['city_id'])
    op.drop_index(op.f('idx_disaster_reports_barangay'), table_name='disaster_reports')
    op.drop_index(op.f('idx_disaster_reports_priority'), table_name='disaster_reports')
    op.drop_index(op.f('idx_disaster_reports_source'), table_name='disaster_reports')
    op.drop_index(op.f('idx_disaster_reports_status'), table_name='disaster_reports')
    op.drop_constraint(op.f('disaster_reports_disaster_type_id_fkey'), 'disaster_reports', type_='foreignkey')
    op.drop_constraint(op.f('disaster_reports_sitio_id_fkey'), 'disaster_reports', type_='foreignkey')
    op.drop_constraint(op.f('disaster_reports_user_id_fkey'), 'disaster_reports', type_='foreignkey')
    op.drop_constraint(op.f('disaster_reports_barangay_id_fkey'), 'disaster_reports', type_='foreignkey')
    op.create_foreign_key(None, 'disaster_reports', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'disaster_reports', 'disaster_types', ['disaster_type_id'], ['disaster_type_id'])
    op.create_foreign_key(None, 'disaster_reports', 'sitios', ['sitio_id'], ['sitio_id'])
    op.create_foreign_key(None, 'disaster_reports', 'barangays', ['barangay_id'], ['barangay_id'])
    op.drop_constraint(op.f('fk_org_approved_by'), 'organizations', type_='foreignkey')
    op.create_foreign_key('fk_org_approved_by', 'organizations', 'users', ['approved_by_user_id'], ['user_id'])
    op.drop_constraint(op.f('organizations_status_check'), 'organizations', type_='check')
    op.create_check_constraint('chk_organizations_status', 'organizations', "status::text = ANY (ARRAY['Pending','Approved','Rejected']::text[])")
    op.drop_index(op.f('idx_physical_donations_guest'), table_name='physical_donations')
    op.drop_index(op.f('idx_physical_donations_report'), table_name='physical_donations')
    op.drop_index(op.f('idx_physical_donations_report_status'), table_name='physical_donations')
    op.drop_index(op.f('idx_physical_donations_status'), table_name='physical_donations')
    op.drop_index(op.f('idx_physical_donations_user'), table_name='physical_donations')
    op.drop_constraint(op.f('physical_donations_guest_donor_id_fkey'), 'physical_donations', type_='foreignkey')
    op.drop_constraint(op.f('physical_donations_user_id_fkey'), 'physical_donations', type_='foreignkey')
    op.drop_constraint(op.f('physical_donations_item_id_fkey'), 'physical_donations', type_='foreignkey')
    op.drop_constraint(op.f('physical_donations_report_id_fkey'), 'physical_donations', type_='foreignkey')
    op.create_foreign_key(None, 'physical_donations', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'physical_donations', 'disaster_reports', ['report_id'], ['report_id'])
    op.create_foreign_key(None, 'physical_donations', 'guest_donors', ['guest_donor_id'], ['guest_donor_id'])
    op.create_foreign_key(None, 'physical_donations', 'items', ['item_id'], ['item_id'])
    op.drop_constraint(op.f('received_goods_received_by_user_id_fkey'), 'received_goods', type_='foreignkey')
    op.drop_constraint(op.f('received_goods_donation_id_fkey'), 'received_goods', type_='foreignkey')
    op.create_foreign_key(None, 'received_goods', 'physical_donations', ['donation_id'], ['donation_id'])
    op.create_foreign_key(None, 'received_goods', 'users', ['received_by_user_id'], ['user_id'])
    op.drop_constraint(op.f('sitios_barangay_id_fkey'), 'sitios', type_='foreignkey')
    op.create_foreign_key(None, 'sitios', 'barangays', ['barangay_id'], ['barangay_id'])
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_assigned_barangay'), table_name='users')
    op.drop_index(op.f('idx_users_organization'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_role'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_users_organization'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('idx_users_assigned_barangay'), 'users', ['assigned_barangay_id'], unique=False)
    op.alter_column('users', 'contact_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'sitios', type_='foreignkey')
    op.create_foreign_key(op.f('sitios_barangay_id_fkey'), 'sitios', 'barangays', ['barangay_id'], ['barangay_id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'received_goods', type_='foreignkey')
    op.drop_constraint(None, 'received_goods', type_='foreignkey')
    op.create_foreign_key(op.f('received_goods_donation_id_fkey'), 'received_goods', 'physical_donations', ['donation_id'], ['donation_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('received_goods_received_by_user_id_fkey'), 'received_goods', 'users', ['received_by_user_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'physical_donations', type_='foreignkey')
    op.drop_constraint(None, 'physical_donations', type_='foreignkey')
    op.drop_constraint(None, 'physical_donations', type_='foreignkey')
    op.drop_constraint(None, 'physical_donations', type_='foreignkey')
    op.create_foreign_key(op.f('physical_donations_report_id_fkey'), 'physical_donations', 'disaster_reports', ['report_id'], ['report_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('physical_donations_item_id_fkey'), 'physical_donations', 'items', ['item_id'], ['item_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('physical_donations_user_id_fkey'), 'physical_donations', 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('physical_donations_guest_donor_id_fkey'), 'physical_donations', 'guest_donors', ['guest_donor_id'], ['guest_donor_id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_physical_donations_user'), 'physical_donations', ['user_id'], unique=False)
    op.create_index(op.f('idx_physical_donations_status'), 'physical_donations', ['status'], unique=False)
    op.create_index(op.f('idx_physical_donations_report_status'), 'physical_donations', ['report_id', 'status'], unique=False)
    op.create_index(op.f('idx_physical_donations_report'), 'physical_donations', ['report_id'], unique=False)
    op.create_index(op.f('idx_physical_donations_guest'), 'physical_donations', ['guest_donor_id'], unique=False)
    op.drop_constraint('chk_organizations_status', 'organizations', type_='check')
    op.create_check_constraint(op.f('organizations_status_check'), 'organizations', "status::text = ANY (ARRAY['Pending'::character varying, 'Approved'::character varying, 'Rejected'::character varying]::text[])")
    op.drop_constraint('fk_org_approved_by', 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_org_approved_by'), 'organizations', 'users', ['approved_by_user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'disaster_reports', type_='foreignkey')
    op.drop_constraint(None, 'disaster_reports', type_='foreignkey')
    op.drop_constraint(None, 'disaster_reports', type_='foreignkey')
    op.drop_constraint(None, 'disaster_reports', type_='foreignkey')
    op.create_foreign_key(op.f('disaster_reports_barangay_id_fkey'), 'disaster_reports', 'barangays', ['barangay_id'], ['barangay_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('disaster_reports_user_id_fkey'), 'disaster_reports', 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('disaster_reports_sitio_id_fkey'), 'disaster_reports', 'sitios', ['sitio_id'], ['sitio_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('disaster_reports_disaster_type_id_fkey'), 'disaster_reports', 'disaster_types', ['disaster_type_id'], ['disaster_type_id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_disaster_reports_status'), 'disaster_reports', ['status'], unique=False)
    op.create_index(op.f('idx_disaster_reports_source'), 'disaster_reports', ['source'], unique=False)
    op.create_index(op.f('idx_disaster_reports_priority'), 'disaster_reports', ['priority_level'], unique=False)
    op.create_index(op.f('idx_disaster_reports_barangay'), 'disaster_reports', ['barangay_id'], unique=False)
    op.drop_constraint(None, 'barangays', type_='foreignkey')
    op.create_foreign_key(op.f('barangays_city_id_fkey'), 'barangays', 'cities', ['city_id'], ['city_id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_barangays_city'), 'barangays', ['city_id'], unique=False)
    # ### end Alembic commands ###
