"""add uploads table (Sprint 0 upload service)

Revision ID: 543599c29c03
Revises: 142a5db2006c
Create Date: 2026-10-01

HAND-WRITTEN, not autogenerated. Autogenerate would also re-emit the
index/FK drops from 142a5db2006c because the models don't declare them
yet (fixed separately in the drift-repair revision). This file only
creates one new table and touches nothing that exists.

Before applying: `alembic heads` must print exactly one head, and it
must equal down_revision below. If not, change down_revision to it.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "543599c29c03"
down_revision: Union[str, Sequence[str], None] = "142a5db2006c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "uploads",
        sa.Column("upload_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("file_id", sa.String(36), nullable=False),
        sa.Column("purpose", sa.String(40), nullable=False),
        sa.Column("visibility", sa.String(10), nullable=False),
        sa.Column("content_type", sa.String(50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("storage_key", sa.String(255), nullable=False),
        sa.Column(
            "owner_user_id",
            sa.Integer(),
            sa.ForeignKey("users.user_id", ondelete="SET NULL", name="fk_uploads_owner_user_id"),
            nullable=True,
        ),
        sa.Column("claim_token_hash", sa.String(64), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("visibility IN ('private', 'public')", name="chk_uploads_visibility"),
        sa.CheckConstraint("size_bytes > 0", name="chk_uploads_size"),
        sa.UniqueConstraint("storage_key", name="uq_uploads_storage_key"),
    )
    op.create_index("ix_uploads_file_id", "uploads", ["file_id"], unique=True)
    op.create_index("ix_uploads_owner_user_id", "uploads", ["owner_user_id"])


def downgrade() -> None:
    op.drop_index("ix_uploads_owner_user_id", table_name="uploads")
    op.drop_index("ix_uploads_file_id", table_name="uploads")
    op.drop_table("uploads")