"""add barangay_donation_methods (several payment methods per barangay, J3)

Revision ID: a7c3e91b5d24
Revises: dcda2d8a846c
Create Date: 2026-10-05

HAND-WRITTEN, not autogenerated. Creates one new table and copies the
existing barangay_donation_info rows into it as each barangay's first
method. barangay_donation_info itself is left in place (now unused by the
API) so nothing is lost; drop it in a later migration once this is stable.

A barangay may now publish several ways to receive money (for example a
GCash QR, a Maya QR and a bank account), each with its own provider,
account details, instructions and QR image. DISPLAY ONLY: NexaAid never
processes, holds or verifies money (manuscript Scope Limitation #5).

Before applying: `alembic heads` must print exactly one head, and it must
equal down_revision below. If not, change down_revision to it.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a7c3e91b5d24"
down_revision: Union[str, Sequence[str], None] = "dcda2d8a846c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "barangay_donation_methods"


def upgrade() -> None:
    op.create_table(
        TABLE,
        sa.Column("method_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "barangay_id", sa.Integer(),
            sa.ForeignKey("barangays.barangay_id", ondelete="CASCADE",
                          name=f"fk_{TABLE}_barangay"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(20), nullable=True),
        sa.Column("account_name", sa.String(100), nullable=True),
        sa.Column("account_number", sa.String(50), nullable=True),
        sa.Column("instructions", sa.String(500), nullable=True),
        sa.Column(
            "qr_file_id", sa.String(36),
            sa.ForeignKey("uploads.file_id", ondelete="SET NULL", name=f"fk_{TABLE}_qr_file_id"),
            nullable=True,
        ),
        sa.Column(
            "updated_by_user_id", sa.Integer(),
            sa.ForeignKey("users.user_id", ondelete="SET NULL", name=f"fk_{TABLE}_updated_by"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "provider IS NULL OR provider IN ('GCash', 'Maya', 'Bank', 'Other')",
            name=f"chk_{TABLE}_provider",
        ),
        sa.CheckConstraint(
            "qr_file_id IS NOT NULL OR account_number IS NOT NULL OR instructions IS NOT NULL",
            name=f"chk_{TABLE}_has_info",
        ),
    )
    op.create_index(f"ix_{TABLE}_barangay_id", TABLE, ["barangay_id"])

    # Each barangay's existing single record becomes its first method.
    op.execute(
        f"""
        INSERT INTO {TABLE}
            (barangay_id, provider, account_name, account_number, instructions,
             qr_file_id, updated_by_user_id, updated_at)
        SELECT barangay_id, provider, account_name, account_number, instructions,
               qr_file_id, updated_by_user_id, updated_at
        FROM barangay_donation_info
        ORDER BY barangay_id
        """
    )


def downgrade() -> None:
    # The old barangay_donation_info table is untouched by upgrade(), so it
    # still holds the pre-upgrade data; only methods added since are lost.
    op.drop_index(f"ix_{TABLE}_barangay_id", table_name=TABLE)
    op.drop_table(TABLE)
