"""add barangay_donation_info and report_donation_info (adviser item 7)

Revision ID: dcda2d8a846c
Revises: f3dd12dbc3d7
Create Date: 2026-10-03

HAND-WRITTEN, not autogenerated. Creates two new tables and touches
nothing that exists (disaster_reports and barangays are unchanged).

Where donors can send money directly to a barangay: an optional QR image
(an upload with purpose barangay_donation_qr) and/or text (provider,
account name, account number, instructions). DISPLAY ONLY: NexaAid never
processes, holds or verifies money (manuscript Scope Limitation #5).

- barangay_donation_info: the barangay's default, edited by its Barangay
  Receiving Representative or the Administrator.
- report_donation_info: optional override for one report, set by the
  CSWS Disaster Unit (UC-CD1). Without it the report shows the default.

Before applying: `alembic heads` must print exactly one head, and it must
equal down_revision below. If not, change down_revision to it.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "dcda2d8a846c"
down_revision: Union[str, Sequence[str], None] = "f3dd12dbc3d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _info_columns(prefix: str) -> list:
    """The columns both tables share. Constraint names get the table prefix."""
    return [
        sa.Column("provider", sa.String(20), nullable=True),
        sa.Column("account_name", sa.String(100), nullable=True),
        sa.Column("account_number", sa.String(50), nullable=True),
        sa.Column("instructions", sa.String(500), nullable=True),
        sa.Column(
            "qr_file_id", sa.String(36),
            sa.ForeignKey("uploads.file_id", ondelete="SET NULL", name=f"fk_{prefix}_qr_file_id"),
            nullable=True,
        ),
        sa.Column(
            "updated_by_user_id", sa.Integer(),
            sa.ForeignKey("users.user_id", ondelete="SET NULL", name=f"fk_{prefix}_updated_by"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "provider IS NULL OR provider IN ('GCash', 'Maya', 'Bank', 'Other')",
            name=f"chk_{prefix}_provider",
        ),
        sa.CheckConstraint(
            "qr_file_id IS NOT NULL OR account_number IS NOT NULL OR instructions IS NOT NULL",
            name=f"chk_{prefix}_has_info",
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "barangay_donation_info",
        sa.Column(
            "barangay_id", sa.Integer(),
            sa.ForeignKey("barangays.barangay_id", ondelete="CASCADE",
                          name="fk_barangay_donation_info_barangay"),
            primary_key=True,
        ),
        *_info_columns("barangay_donation_info"),
    )
    op.create_table(
        "report_donation_info",
        sa.Column(
            "report_id", sa.Integer(),
            sa.ForeignKey("disaster_reports.report_id", ondelete="CASCADE",
                          name="fk_report_donation_info_report"),
            primary_key=True,
        ),
        *_info_columns("report_donation_info"),
    )


def downgrade() -> None:
    op.drop_table("report_donation_info")
    op.drop_table("barangay_donation_info")
