"""add users.id_type (UC-D1 step 3: kind of valid ID the donor uploaded)

Revision ID: f3dd12dbc3d7
Revises: 543599c29c03
Create Date: 2026-10-03

HAND-WRITTEN, not autogenerated (autogenerate would also try to drop the
indexes the models don't declare, see 142a5db2006c). Adds one nullable
column, so existing rows are untouched: donors who registered before this
change, staff, and organizations simply have NULL.

Allowed values are checked in schemas/user_schema.py (ID_TYPES), not with
a database CHECK, so the list can grow without another migration.

Before applying: `alembic heads` must print exactly one head, and it must
equal down_revision below. If not, change down_revision to it.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f3dd12dbc3d7"
down_revision: Union[str, Sequence[str], None] = "543599c29c03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("users", sa.Column("id_type", sa.String(40), nullable=True))


def downgrade() -> None:
    op.drop_column("users", "id_type")
